version: '3'
services:
  redis:
    image: "redis:4.0-alpine"

  db:
    image: 'postgres:9.6'
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file: .env
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
