default: &default
  host: <%= ENV.fetch('APPLICATION_HOST') %>
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>

  database:
    max_connections: <%= ENV.fetch('DATABASE_MAX_CONNECTIONS') %>
    username: <%= ENV.fetch('DATABASE_USERNAME') %>
    password: <%= ENV.fetch('DATABASE_PASSWORD') %>
    host: <%= ENV.fetch('DATABASE_HOST') %>
    port: <%= ENV.fetch('DATABASE_PORT') %>
    name: <%= ENV.fetch('DATABASE_NAME') %>
    encoding: <%= ENV.fetch('DATABASE_ENCODING') %>

  jwt:
    password: <%= ENV.fetch('JWT_PASSWORD') %>

  aws:
    s3:
      use: <%= ENV.fetch('AWS_S3_USE') == 'true' %>
      access_key_id: <%= ENV.fetch('AWS_S3_ACCESS_KEY_ID') %>
      secret_access_key: <%= ENV.fetch('AWS_S3_SECRET_ACCESS_KEY') %>
      region: <%= ENV.fetch('AWS_S3_REGION') %>
      bucket: <%= ENV.fetch('AWS_S3_BUCKET') %>

  fedex:
    password: <%= ENV.fetch('FEDEX_PASSWORD') %>
    key: <%= ENV.fetch('FEDEX_KEY') %>
    account_number: <%= ENV.fetch('FEDEX_ACCOUNT_NUMBER') %>
    meter_number: <%= ENV.fetch('FEDEX_METER_NUMBER') %>
    test_mode: <%= ENV.fetch('FEDEX_TEST_MODE') == 'true' %>

  shipping:
    origin:
      country: <%= ENV.fetch('SHIPPING_ORIGIN_COUNTRY') %>
      state: <%= ENV.fetch('SHIPPING_ORIGIN_STATE') %>
      city: <%= ENV.fetch('SHIPPING_ORIGIN_CITY') %>
      zip: <%= ENV.fetch('SHIPPING_ORIGIN_ZIP') %>
      address: <%= ENV.fetch('SHIPPING_ORIGIN_ADDRESS') %>

  stripe:
    publishable_key: <%= ENV.fetch('STRIPE_PUBLISHABLE_KEY') %>
    secret_key: <%= ENV.fetch('STRIPE_SECRET_KEY') %>

  mailgun:
    api_key: <%= ENV.fetch('MAILGUN_API_KEY') %>
    domain: <%= ENV.fetch('MAILGUN_DOMAIN') %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
